server:
  port: 8080
  servlet:
    context-path: /

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

spring:
  application:
    name: APIGATEWAY
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOriginPatterns:
              - "http://127.0.0.1:8000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
                  - "*"
            allowCredentials: true
      httpclient:
        connect-timeout: 20000
        response-timeout: 7s
      routes:
        - id: orderservice
          uri: lb://ORDERSERVICE
          predicates:
            - Path=/orders/**
          filters:
            - StripPrefix=1
        - id: customerservice
          uri: lb://CUSTOMERSERVICE
          predicates:
            - Path=/customers/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
        display-name: API Gateway Service
      - url: /CUSTOMERSERVICE/v3/api-docs
        name: Customer Service
        display-name: Customer Service
      - url: /ORDERSERVICE/v3/api-docs
        name: Order Service
        display-name: Order Service